"""add author_id and created_at to decisions

Revision ID: c57196d53c6b
Revises: 13db89c8d85b
Create Date: 2026-09-03 19:31:21.964600

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c57196d53c6b'
down_revision: Union[str, Sequence[str], None] = '13db89c8d85b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decisions', sa.Column('author_id', sa.Integer(), nullable=True))
    op.add_column('decisions', sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False))
    op.create_foreign_key(None, 'decisions', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'decisions', type_='foreignkey')
    op.drop_column('decisions', 'created_at')
    op.drop_column('decisions', 'author_id')
    # ### end Alembic commands ###
